name: endpoints
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Implementation of Dart Server Side Endpoints
homepage: https://github.com/dart-lang/dart_endpoints
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  appengine: '>=0.2.0 <0.3.0'
  googleapis: '>=0.3.0 <0.5.0'
  http: '>=0.11.1 <0.12.0'
  shelf_appengine: '>=0.1.0 <0.2.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
